.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/AnyJSONType.swift
Sources/PubNub/Helpers/JSONCodable.swift
Sources/PubNub/Helpers/PubNubAPNSPayload.swift
Sources/PubNub/Helpers/PubNubPushMessage.swift
Sources/PubNub/Networking/Routers/PushRouter.swift
Sources/PubNub/PubNub.swift
Sources/PubNub/Subscription/SubscriptionSession.swift
Tests/PubNubTests/Integration/PublishEndpointIntegrationTests.swift
Tests/PubNubTests/Integration/SubscriptionIntegrationTests.swift

Proposed 2.3.1 release includes the following:
- Server team updated the PubNub Push Config to include an additional field.
- Fixed an issue if a scalar value was published inside the push payload. I followed the Android structure of adding 'data' as the key
- Updated some of the push doc headers to provide more clarity in their usage
- Fixed an issue with subscribe continuously trying to reconnect to the loop in the even of an unexpected disconnect.  Short term solution is to manually reconnect, but an automatic solution should be added.

Fixed a couple issues related to APNS2 payload publishing

---

Sources/PubNub/Networking/Routers/SubscribeRouter.swift

Make `region` optional during `originTimetoken` parsing (not guaranteed to be set) and assign 0 by default (if missing).
_This approach will affect only `originTimetoken` and it is not critical to have `region` set to 0 there, because it is not used anywhere in requests. Subscribe response timetoken and publish timetokens guaranteed has `region` data._

Fix originTimetokn 'region' parsing crash

---

.pubnub.yml
PubNubSwift.podspec

Make `region` optional during `originTimetoken` parsing and set to **0** by default.

PubNub SDK 2.4.2 Release

---

.pubnub.yml
Sources/PubNub/Networking/Response/GenericServicePayloadResponse.swift

This is a minor patch fix to include a custom error message (from Functions) inside the error payload.  
Example usage would be a function aborts a request with a custom message:
```
export default (request) => {
request.status = 400
return request.abort('Message dropped')
};
```
The resulting error can be filtered using:
```  
pubnub.publish(channel: "shouldFail", message: payload) { result in
switch result {
case let .success(response):
print("Successful Publish Response: \(response)")
case let .failure(error as PubNubError):
if error.reason == .badRequest && error.details.contains("Message dropped") {
print("Publish Rejected from Function: \(error)")
} else {
print("Failed Publish Response: \(error)")
}
case let .failure(error):
print("Failed Publish Response: \(error)")
}
}
```

Custom error messages (from functions) will be included inside PubNubError

---

.pubnub.yml

Rename `enchancement` change type to `improvement` which which match requirement of validation schema.

docs: fix change type in .pubnub.yml

---

Sources/PubNub/Helpers/Crypto/Crypto.swift
Tests/PubNubTests/Helpers/CryptoTests.swift
Tests/PubNubTests/Networking/Routers/HistoryRouterTests.swift

Crypto by default initialized with `randomizeIV` set to `true` which will encrypt / decrypt data with publish / subscribe / history API calls using randomized initialization vector.
**Warning:** This PR contains **BREAKING CHANGES** which affects how messages are sent with enabled encryption. Randomized IV used by default will make old data inaccessible w/o explicit switch to static IV usage.

Use randomized IV by default

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec

Crypto by default initialized with `randomizeIV` set to `true` which will encrypt / decrypt data with publish / subscribe / history API calls using randomized initialization vector.
Add new `sdks` section to `.pubnub.yml` with information about available artifacts and distribution variants.

PubNub SDK 4.0.0 Release

---

Sources/PubNub/Errors/ErrorDescription.swift
Sources/PubNub/Networking/Routers/PushRouter.swift
Tests/PubNubTests/Networking/Routers/PushRouterTests.swift

Don't perform HEX-encoding of `Data` with FCM token which should be used as-is.

Don't convert FCM token to HEX

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
README.md
Sources/PubNub/Helpers/Constants.swift

feat(pam): add token parse
Add ability to parse permissions from token provided by servers.
refactor(pam): token has higher priority for 'auth'
Use `token` instead of `authKey` (if specified) for query `auth`.
fix(files): fix files encryption / decryption
Fix `bufferTooSmall` and make temporary buffers for files encryption / decryption adaptive in size to provided stream buffer size.
fix(push): don't convert FCM token to HEX
Don't perform HEX-encoding of `Data` with FCM token which should be used as-is.
feat: add support for components
Make it possible to add component identifiers for requests.

PubNub SDK 4.1.0

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/Constants.swift
Sources/PubNub/Models/PubNubChannelMetadata.swift
Sources/PubNub/Models/PubNubUUIDMetadata.swift
Sources/PubNub/Networking/Routers/ObjectsChannelRouter.swift
Sources/PubNub/Networking/Routers/ObjectsMembershipsRouter.swift
Sources/PubNub/Networking/Routers/ObjectsUUIDRouter.swift
Sources/PubNub/Networking/Routers/Subscribe Payloads/SubscribeObjectPayload.swift
Tests/PubNubTests/Networking/Routers/ObjectsMembershipsRouterTests.swift
Tests/PubNubTests/Networking/Routers/SubscribeRouterTests.swift

fix: make 'name' field optional
Make `name` field optional for channel and UUID metadata.

Make 'name' field optional

---

.pubnub.yml
Examples/Example-iOS/Info.plist
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/Constants.swift
Sources/PubNub/PubNub.swift
Sources/PubNub/Subscription/SubscribeSessionFactory.swift
Sources/PubNub/Subscription/SubscriptionSession.swift
Tests/PubNubTests/Helpers/PAMTokenTests.swift

fix(pamv3): fix token in subscription session
Fix issue because of which access token not updated in subscription session.

fix(pamv3): fix token in subscription session

---

.pubnub.yml
Examples/Sources/MasterDetailTableViewController.swift
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Errors/PubNubError.swift
Sources/PubNub/Helpers/Constants.swift
Sources/PubNub/Networking/Response/GenericServicePayloadResponse.swift
Sources/PubNub/Networking/Response/ResponseOperator.swift
Sources/PubNub/Subscription/SubscriptionSession.swift

feat(error): add affected resources in error
Add affected channels and groups under `affected` resources list.

feat(error): add affected resources in error

---

.github/workflows/release/versions.json
.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec

feat: VSP methods and models have been exposed via modules on the PubNub instance
feat: `FlatJSONCodable` replaces `[String: JSONCodableScalar]` inside the VSP models
refactor: PubNub instances has been changed from a `struct` to a `class`
refactor: `HTTPSession` has been made public for easier per-request overrides of the Network Session

Fixing up release information for VSP modules.

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/Constants.swift
Sources/PubNub/Subscription/SubscriptionSession.swift

fix(listener): fix listeners retain cycle
Fix issue because of which listener wasn't `deinit` even when reference on it has been nullified.
Closes #92

Fix listeners retain cycle

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/Constants.swift
Tests/PubNubTests/Push/PubNubPushTargetTests.swift

fix(notifications): uppercasing the excluded_devices field
Uppercasing of the `excluded_devices` field to match the format expected by the REST API

Added an additional test case for excluded_devices

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/Constants.swift

feat(cocoapods): make `static_framework` configurable in the spec file
To make client integration more flexible for different projects setup, the `$PubNubAsStaticFramework` flag has been added to `PubNubSwift.podspec`. 
With `$PubNubAsStaticFramework = true` in `Podfile` SDK will be integrated as a static library.
Closes #142

Make `static_framework` flag configurable

---

.pubnub.yml
Examples/Sources/ConfigDetailTableViewController.swift
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/APIs/File+PubNub.swift
Sources/PubNub/Extensions/URLRequest+PubNub.swift
Sources/PubNub/Helpers/Constants.swift
Sources/PubNub/Helpers/Crypto/Crypto.swift
Sources/PubNub/Helpers/Crypto/CryptoModule.swift
Sources/PubNub/Networking/HTTPFileTask.swift
Sources/PubNub/Networking/HTTPRouter.swift
Sources/PubNub/Networking/Routers/HistoryRouter.swift
Sources/PubNub/Networking/Routers/PublishRouter.swift
Sources/PubNub/Networking/Routers/SubscribeRouter.swift
Sources/PubNub/PubNub.swift
Sources/PubNub/PubNubConfiguration.swift
Sources/PubNub/Subscription/SubscribeSessionFactory.swift
Tests/PubNubContractTest/Steps/CryptorModule/PubNubCryptoModuleContractTestSteps.swift
Tests/PubNubContractTest/Steps/Subscribe/PubNubSubscribeContractTestSteps.swift
Tests/PubNubTests/Helpers/CryptoTests.swift
Tests/PubNubTests/Networking/Routers/HistoryRouterTests.swift
Tests/PubNubTests/PubNubConfigurationTests.swift

fix(crypto): Renaming `CryptorModule` with `CryptoModule`
Align on namings across all supported platforms

fix(crypto): Renaming CryptorModule with CryptoModule

---

.pubnub.yml
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/Helpers/Constants.swift
Sources/PubNub/Models/PubNubMessage.swift
Sources/PubNub/Networking/Routers/HistoryRouter.swift
Sources/PubNub/Networking/Routers/SubscribeRouter.swift
Tests/PubNubTests/Mocking/Responses/Subscribe/subscription_encrypted_message_success.json
Tests/PubNubTests/Networking/Routers/HistoryRouterTests.swift
Tests/PubNubTests/Networking/Routers/SubscribeRouterTests.swift

fix(crypto): handle unencrypted message while getting it with CryptoModule configured

Returning the original message in case of decryption failure

---

Package.swift
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
README.md

- Upgarding deployment targets to minimum deployment targets suggested by `Xcode 15.3`:
- `iOS 12.0` and above
- `tvOS 12.0` and above
- `watchOS 4.0` and above
- `macOS 10.13` and above
- Updating `README.md`

Upgrading deployment targets

---

README.md

I missed that the instruction for fetching PubNub SDK via Swift Package Manager is also outdated. This PR fixes it.

Updating instructions for fetching PubNub SDK via SPM

---

Package.swift
PubNub.xcodeproj/project.pbxproj
PubNubSwift.podspec
Sources/PubNub/PrivacyInfo.xcprivacy

feat(privacy-manifest): Adding PrivacyInfo.xcprivacy

Adding PrivacyInfo.xcprivacy

---

.github/workflows/release.yml

build(workflow): add missing Ruby installation steps

build(workflow): add missing Ruby installation steps
